### ISSUE TITLE
Error: Can't resolve './locale'

### ISSUE THREAD

**Issue by dlrice** [geneontology/wc-gocam-viz#74]
Hi, with v1.1.1 I am encountering this error:

```
WARNING in ./node_modules/@geneontology/wc-gocam-viz/dist/esm/go-loading-spinner_4.entry.js 33653:12-46

Module not found: Error: Can't resolve './locale' in '/Users/dlrice/Developer/uniprot-website/d/node_modules/@geneontology/wc-gocam-viz/dist/esm'
```

Are you seeing this on your side? Searching online I end up at a moment github issue [Webpack Error: Cannot find module "./locale" after updating to 2.19.0 ](https://github.com/moment/moment/issues/4216) from 2017 but still seems to affect some people as seen in this [comment](https://github.com/moment/moment/issues/4216#issuecomment-2242717465) where they needed to downgrade Moment to 2.18.1.

**Comment by dlrice** [comment]
Thanks @pkalita-lbl for your response and quick review of my PRs.

**Comment by pkalita-lbl** [comment]
Happy to. I can also put out a new patch release soon, unless you have more changes coming.

**Comment by dlrice** [comment]
Just created this PR https://github.com/geneontology/wc-gocam-viz/pull/79 and after this I don't plan any more changes. If possible a patch next week would be appreciated then I can deploy the wc-gocam-viz to our production site. Thanks!

**Comment by pkalita-lbl** [comment]
@dlrice the fix for this issue has now been released as part of [version `1.1.2`](https://github.com/geneontology/wc-gocam-viz/releases/tag/v1.1.2)
